"""Repository ports.

Services depend on these protocols, not on any concrete store. The default in-memory
adapters implement them for local and test use; a cloud deployment provides SQL,
DynamoDB or other adapters with the same surface, so switching persistence is a wiring
change rather than a code change. This is the seam that makes the layer cloud-ready.
"""

from __future__ import annotations

from typing import Protocol

from ..domain.models import ApiKey, AuditEntry, Project, Role, Team, User, Workspace


class WorkspaceRepository(Protocol):
    def add(self, workspace: Workspace) -> Workspace: ...
    def get(self, workspace_id: str) -> Workspace | None: ...
    def get_by_slug(self, slug: str) -> Workspace | None: ...
    def list(self) -> list[Workspace]: ...


class UserRepository(Protocol):
    def add(self, user: User) -> User: ...
    def get(self, user_id: str) -> User | None: ...
    def get_by_email(self, workspace_id: str, email: str) -> User | None: ...
    def list(self, workspace_id: str) -> list[User]: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: str) -> bool: ...


class RoleRepository(Protocol):
    def add(self, role: Role) -> Role: ...
    def get(self, workspace_id: str, name: str) -> Role | None: ...
    def list(self, workspace_id: str) -> list[Role]: ...
    def delete(self, workspace_id: str, name: str) -> bool: ...


class ProjectRepository(Protocol):
    def add(self, project: Project) -> Project: ...
    def get(self, project_id: str) -> Project | None: ...
    def list(self, workspace_id: str) -> list[Project]: ...
    def update(self, project: Project) -> Project: ...
    def delete(self, project_id: str) -> bool: ...


class TeamRepository(Protocol):
    def add(self, team: Team) -> Team: ...
    def get(self, team_id: str) -> Team | None: ...
    def list(self, workspace_id: str) -> list[Team]: ...
    def update(self, team: Team) -> Team: ...
    def delete(self, team_id: str) -> bool: ...


class ApiKeyRepository(Protocol):
    def add(self, key: ApiKey) -> ApiKey: ...
    def get_by_public_id(self, public_id: str) -> ApiKey | None: ...
    def list(self, workspace_id: str) -> list[ApiKey]: ...
    def update(self, key: ApiKey) -> ApiKey: ...


class AuditRepository(Protocol):
    def add(self, entry: AuditEntry) -> AuditEntry: ...
    def query(
        self,
        workspace_id: str,
        *,
        actor_id: str | None = None,
        action: str | None = None,
        limit: int = 100,
    ) -> list[AuditEntry]: ...
